/*
 * Accepted -> 1
 * Refused -> 0
 * Waiting -> -1
 */
export const reservations = [
  {
    resevationId: 1,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: -1,
  },
  {
    resevationId: 2,
    asignament: "Elementos de programacion",
    teachers: [
      "Vladimir Costas ",
      "Leticia Blanco ",
      "Rosemary Torrico ",
      "Jorge Orellana ",
      "Marko Antonio Montecinos ",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 3,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: -1,
  },
  {
    resevationId: 4,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 0,
  },
  {
    resevationId: 5,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 0,
  },
  {
    resevationId: 6,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 7,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 8,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 9,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 10,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: -1,
  },
  {
    resevationId: 11,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 12,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 0,
  },
  {
    resevationId: 13,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: 1,
  },
  {
    resevationId: 14,
    asignament: "Introduccion a la programacion",
    teachers: [
      "Vladimir Costas",
      "Leticia Blanco",
      "Rosemary Torrico",
      "Jorge Orellana",
      "Marko Antonio Montecinos",
    ],
    groups: [3, 2, 10],
    reason: "Examen de primer pacial",
    environment: "Auditorio",
    reservationDate: "29/03/2024",
    schedule: "11:15-14:15",
    academicPeriods: 6,
    capacity: 300,
    state: -1,
  },
];
